/**
 * Every string the cashier reads, in one place.
 *
 * Urdu is a future option (spec §6.2). Keeping display text here means
 * localisation is one file swap rather than a hunt through components — so do
 * not hard-code user-facing text in a component.
 *
 * House style: sentence case, and buttons name the action ("Send to kitchen",
 * "Charge"), never "Submit" or "OK".
 */
export const strings = {
  app: {
    name: 'Food Point',
    by: 'Code Hustlers',
  },

  nav: {
    dashboard: 'Dashboard',
    newOrder: 'New order',
    orders: 'Orders',
    tables: 'Tables',
    menu: 'Menu',
    deals: 'Deals',
    reports: 'Reports',
    cancellations: 'Cancellations',
    customers: 'Customers',
    sales: 'Sales',
    settings: 'Settings',
  },

  deals: {
    title: 'Deals',
    subtitle: 'Bundles sold at one combo price.',
    addDeal: 'Add deal',
    editDeal: 'Edit deal',
    name: 'Deal name',
    namePlaceholder: 'e.g. Family Deal',
    price: 'Combo price',
    priceHint: 'What the customer pays for the whole bundle.',
    contents: 'What is in it',
    addItem: 'Add an item',
    active: 'On the order screen',
    inactive: 'Off',
    menuValue: 'Parts separately',
    saving: 'Customer saves',
    markup: 'Priced above the parts',
    unavailable: 'Unavailable',
    soldOutBecause: (item: string) => `${item} is sold out`,
    noItemsYet: 'No items in this deal yet.',
    emptyTitle: 'No deals yet',
    emptyNote: 'A deal bundles menu items at one fixed price — Burger + Fries + Drink for Rs 550.',
    deleteConfirm: 'Delete this deal? Past bills keep their record of it.',
    itemsCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    inDeal: 'Deal',
    photo: 'Deal photo',
  },

  staff: {
    title: 'Staff',
    subtitle: 'Who can take orders, and whose name goes on a cancellation.',
    signIn: 'Sign in',
    signOut: 'Sign out',
    switchUser: 'Switch user',
    whoAreYou: 'Who is on the counter?',
    enterPin: 'Enter your PIN',
    pinHint: 'Your own 4-digit PIN, not the manager PIN.',
    signedInAs: 'Signed in',
    addStaff: 'Add staff',
    editStaff: 'Edit staff',
    name: 'Name',
    namePlaceholder: 'e.g. Bilal',
    pin: 'PIN',
    pinSet: 'PIN set',
    noPin: 'No PIN',
    setPin: 'Set a PIN',
    changePin: 'Change PIN',
    pinOptional: 'Leave blank to keep the current PIN.',
    active: 'On the counter',
    inactive: 'Left',
    remove: 'Remove',
    deactivated: 'Removed from the counter — their past cancellations are kept.',
    deleted: 'Removed.',
    emptyTitle: 'No staff added yet',
    emptyNote:
      'Add the people who work the counter. Until you do, cancellations are recorded without a name.',
    signInPrompt: 'Sign in to start taking orders.',
    wrongPin: "That PIN doesn't match.",
  },

  admin: {
    title: 'Admin',
    hint: 'Enter the manager PIN to open the owner’s area.',
    unlock: 'Open admin',
    wrongPin: 'That PIN doesn’t match.',
    backToCounter: 'Back to counter',
    exitAdmin: 'Exit admin',
    adminButton: 'Admin',
    counterArea: 'Counter',
    adminArea: 'Admin',
    setPinTitle: 'Set a manager PIN',
    setPinHint:
      'The admin area holds your takings and settings, so it needs a PIN. This is the same PIN that approves cancelling a paid order.',
    setPinAction: 'Set PIN and continue',
    confirmPin: 'Repeat PIN',
    pinMismatch: 'Those two PINs are not the same.',
    locked: 'Admin locked.',
  },

  theme: {
    dark: 'Dark',
    light: 'Light',
    toLight: 'Switch to the light theme',
    toDark: 'Switch to the dark theme',
  },

  customers: {
    title: 'Customers',
    subtitle: 'Saved by phone number from takeaway and delivery orders.',
    unnamed: 'Saved customer',
    ordersBefore: (n: number) => `${n} order${n === 1 ? '' : 's'} before`,
    search: 'Search name or phone',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    notes: 'Notes',
    orders: 'Orders',
    lastOrder: 'Last order',
    never: 'Never',
    edit: 'Edit customer',
    exportCsv: 'Export CSV',
    exported: (n: number) => `${n} customers exported.`,
    deleteConfirm:
      'Delete this customer? Their past orders are kept — only the saved contact is removed.',
    deleted: 'Customer deleted. Past orders are untouched.',
    emptyTitle: 'No customers yet',
    emptyNote:
      'A customer is saved automatically whenever a takeaway or delivery order is placed with a phone number.',
    noResults: 'Nobody matches that search.',
  },

  extras: {
    title: 'Extras',
    subtitle: 'Packaging and disposables, charged on any order type.',
    add: 'Add extra',
    name: 'Name',
    namePlaceholder: 'e.g. Disposable plates',
    price: 'Price',
    cost: 'Cost to you',
    costHint: 'Optional. Keeps profit honest — plates are not free.',
    active: 'Offered',
    inactive: 'Off',
    none: 'No extras set up yet.',
    onOrder: 'Extras',
    addToOrder: 'Add extras',
    emptyOnOrder: 'No extras on this order.',
    setUpFirst: 'Set extras up in Admin → Settings first.',
  },

  images: {
    photo: 'Photo',
    upload: 'Upload photo',
    replace: 'Replace photo',
    pickExisting: 'Pick existing',
    importFolder: 'Import a whole folder',
    remove: 'Remove',
    noPhoto: 'No photo',
    missingFile: 'Photo file missing',
    pickOne: 'Tap a photo to use it',
    folderEmpty: 'No photos uploaded yet.',
    categoryPhoto: 'Category photo',
    itemPhoto: 'Item photo',
  },

  cancel: {
    title: 'Cancel order',
    cancelOrder: 'Cancel order',
    cancelItem: 'Cancel item',
    reason: 'Why is this being cancelled?',
    note: 'What happened?',
    notePlaceholder: 'Say briefly what happened',
    noteRequired: 'Add a short note when the reason is Other.',
    managerPin: 'Manager PIN',
    paidWarning:
      'This order has already been paid. Cancelling it removes the money from today\'s takings and is recorded permanently against your name.',
    paidPinHint: 'A manager or the owner must enter their PIN to cancel a paid order.',
    unpaidNote: 'Nothing has been paid yet. This will be recorded against your name.',
    confirm: 'Cancel this order',
    confirmItem: 'Cancel this item',
    keep: 'Keep it',
    done: 'Cancelled and recorded.',
  },

  cancellations: {
    title: 'Cancellations',
    subtitle: 'Every cancelled order — who, when, why, and how much.',
    today: 'Today',
    week: 'This week',
    month: 'This month',
    totalCount: 'Cancellations',
    totalValue: 'Total cancelled',
    paidCount: 'Paid orders cancelled',
    paidValue: 'Cash cancelled after payment',
    byStaff: 'By staff member',
    byReason: 'By reason',
    theList: 'Every cancellation',
    staffName: 'Staff',
    count: 'Count',
    value: 'Value',
    paid: 'Paid',
    ofWhichPaid: 'of which paid',
    when: 'When',
    order: 'Order',
    reason: 'Reason',
    amount: 'Amount',
    items: 'Items',
    wasPaid: 'Was paid',
    notRecorded: 'Not recorded',
    emptyTitle: 'No cancellations in this period',
    emptyNote: 'Nothing was cancelled. That is the result you want.',
    watchNote:
      'One person well above the others is worth asking about — especially in the paid column.',
  },

  orders: {
    title: 'Orders',
    subtitle: 'Every order that has been paid or voided.',
    all: 'All',
    settled: 'Paid',
    voided: 'Voided',
    orderNo: 'Order',
    type: 'Type',
    when: 'When',
    items: 'Items',
    payment: 'Payment',
    total: 'Total',
    profit: 'Profit',
    print: 'Print',
    printing: 'Printing…',
    printed: 'Bill sent to the printer.',
    view: 'View',
    viewBill: 'Bill',
    emptyTitle: 'No orders in this range',
    emptyNote: 'Pick a different date range, or take an order to see it here.',
    voidedNote: 'This order was voided and was never paid for.',
  },

  dashboard: {
    title: 'Today',
    salesToday: "Today's sales",
    profitToday: "Today's profit",
    ordersToday: 'Orders today',
    openOrders: 'Open orders',
    bestSeller: 'Best seller today',
    busiestHour: 'Busiest hour',
    today: 'Today',
    recent: 'Recent orders',
    newOrder: 'New order',
    noSalesTitle: 'No orders yet today',
    noSalesNote: 'Takings and profit will appear here as soon as the first order is settled.',
    profitLine: (sales: string, profit: string) => `You sold ${sales} and earned ${profit} profit.`,
  },

  order: {
    newOrder: 'New order',
    dineIn: 'Dine-in',
    takeaway: 'Takeaway',
    delivery: 'Delivery',
    chooseTable: 'Choose a table',
    deliveryAddress: 'Delivery address',
    deliveryAddressHint: 'Required — the rider needs somewhere to go.',
    deliveryAddressPlaceholder: 'House / street / area',
    deliveryCharge: 'Delivery charge',
    phoneLookupHint: 'Type a saved number to fill in the name and address.',
    deliveryNeedsAddress: 'Enter the delivery address before starting the order.',
    customerName: 'Customer name',
    customerPhone: 'Phone',
    optional: 'optional',
    search: 'Search the menu',
    allItems: 'All',
    itemCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    chooseSize: 'Choose a size',
    chooseSizeHint: 'The price changes with the size.',
    from: 'from',
    dealsTab: 'Deals',
    addDeal: 'Add deal to order',
    dealAdded: 'Deal added to the order.',
    sendToKitchen: 'Send to kitchen',
    charge: 'Charge',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    serviceCharge: 'Service charge',
    emptyTitle: 'Nothing on this order yet',
    emptyNote: 'Tap an item on the left to add it.',
    soldOut: 'Sold out',
    fired: 'Sent',
    lineNote: 'Note for the kitchen',
    lineNotePlaceholder: 'e.g. less spicy, no onions',
    addToOrder: 'Add to order',
    void: 'Void',
    voidLine: 'Void this item',
    voidOrder: 'Void the whole order',
    voidReason: 'Why is this being voided?',
    voidReasonPlaceholder: 'e.g. customer changed their mind',
    managerPin: 'Manager PIN',
    paymentMethod: 'Payment',
    cash: 'Cash',
    card: 'Card',
    takePayment: 'Take payment',
    printBill: 'Print bill',
    reprint: 'Reprint bill',
    settled: 'Paid',
    noOpenOrders: 'No orders are open',
    startOrder: 'Start an order',
    resume: 'Resume',
    switchOrder: 'Switch order',
  },

  tables: {
    title: 'Tables',
    free: 'Free',
    occupied: 'Occupied',
    addTable: 'Add table',
    tableName: 'Table name',
    area: 'Area',
    seats: 'Seats',
    emptyTitle: 'No tables yet',
    emptyNote: 'Add your tables and the floor will show which are free at a glance.',
    disabledTitle: 'Tables are switched off',
    disabledNote: 'Turn dine-in tables on in Settings if this food point seats customers.',
  },

  menu: {
    title: 'Menu',
    addItem: 'Add item',
    sizes: 'Sizes',
    sizesHint: 'Add a row for each size. Leave empty for a single-price item.',
    sizeName: 'Size name',
    addSize: 'Add a size',
    noSizes: 'No sizes — this item has one price.',
    addCategory: 'Add category',
    itemName: 'Item name',
    category: 'Category',
    price: 'Price',
    foodCost: 'Food cost',
    foodCostHint: 'Roughly what the ingredients cost. This is what profit is worked out from.',
    available: 'On the menu',
    soldOut: 'Sold out',
    modifierGroups: 'Options',
    emptyTitle: 'Your menu is empty',
    emptyNote: 'Add your first item and it will appear on the order screen straight away.',
    uncategorised: 'Uncategorised',
  },

  reports: {
    title: 'Reports',
    from: 'From',
    to: 'To',
    sales: 'Sales',
    profit: 'Profit',
    orders: 'Orders',
    byType: 'By order type',
    bestSellers: 'Best sellers',
    byHour: 'Sales by hour',
    deliveryTotal: 'Delivery charges',
    extrasTotal: 'Extras & packaging',
    deliveryNote: 'Collected for delivery — no food cost behind it.',
    voids: 'Voids',
    noneTitle: 'Nothing in this range',
    noneNote: 'Pick a different date range to see sales and profit.',
    reason: 'Reason',
    print: 'Print',
  },

  settings: {
    title: 'Settings',
    business: 'Business',
    businessName: 'Business name',
    address: 'Address',
    phone: 'Phone',
    printing: 'Printing',
    customerPrinter: 'Customer bill printer',
    kitchenPrinter: 'Kitchen printer',
    kitchenPrinterHint: 'Leave blank to print kitchen tickets on the customer printer.',
    enableKitchenPrint: 'Print kitchen tickets',
    testPrint: 'Print a test',
    service: 'Charges',
    serviceCharge: 'Service charge %',
    currency: 'Currency symbol',
    dineIn: 'Dine-in',
    enableTables: 'This food point has tables',
    enableTablesHint: 'Turn this off for a pure takeaway counter — the Tables screen disappears.',
    security: 'Voids',
    managerPin: 'Manager PIN',
    deliveryCharge: 'Default delivery charge',
    deliveryChargeHint: 'Pre-filled on a delivery order. Staff can change it per order.',
    slip: 'Receipt slip',
    slipHint: 'Printed at the top and bottom of every customer bill.',
    shopLogo: 'Shop logo',
    shopLogoHint: 'Stored on this computer. Never loaded from the internet.',
    receiptFooter: 'Footer line',
    receiptFooterHint: 'Printed under the thank-you. Leave blank for none.',
    receiptFooterPlaceholder: 'e.g. No refund without receipt',
    slipPreview: 'Slip preview',
    slipPreviewNote:
      'Preview only. The logo is not yet printed on the thermal slip — that is being added separately so live printing cannot break. The printed slip currently shows the shop name and details as text.',
    managerPinHint: 'Ask for this PIN before voiding. Leave it blank to allow voids without one.',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    clearPin: 'Remove PIN',
    backup: 'Backup',
    backupNow: 'Back up now',
    restore: 'Restore from backup',
    lastBackup: 'Last backup',
    neverBackedUp: 'You have never backed up.',
    license: 'License',
    save: 'Save settings',
    saved: 'Settings saved.',
  },

  activation: {
    title: 'Activate Food Point',
    intro:
      'Send this Machine ID to the Code Hustlers office and they will send back a license key for this computer.',
    machineId: 'Machine ID',
    copy: 'Copy',
    copied: 'Copied',
    keyLabel: 'License key',
    keyPlaceholder: 'CH1...',
    activate: 'Activate',
    activating: 'Checking…',
    success: 'Activated. Opening the app…',
  },

  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    loading: 'Loading…',
    search: 'Search',
    none: '—',
    yes: 'Yes',
    no: 'No',
  },
};
