/**
 * Every string the cashier reads, in one place.
 *
 * Urdu is a future option (spec §6.2). Keeping display text here means
 * localisation is one file swap rather than a hunt through components — so do
 * not hard-code user-facing text in a component.
 *
 * House style: sentence case, and buttons name the action ("Send to kitchen",
 * "Charge"), never "Submit" or "OK".
 */
export const strings = {
  app: {
    name: 'Food Point',
    by: 'Code Hustlers',
  },

  nav: {
    dashboard: 'Dashboard',
    newOrder: 'New order',
    orders: 'Orders',
    tables: 'Tables',
    menu: 'Menu',
    reports: 'Reports',
    settings: 'Settings',
  },

  orders: {
    title: 'Orders',
    subtitle: 'Every order that has been paid or voided.',
    all: 'All',
    settled: 'Paid',
    voided: 'Voided',
    orderNo: 'Order',
    type: 'Type',
    when: 'When',
    items: 'Items',
    payment: 'Payment',
    total: 'Total',
    profit: 'Profit',
    print: 'Print',
    printing: 'Printing…',
    printed: 'Bill sent to the printer.',
    view: 'View',
    viewBill: 'Bill',
    emptyTitle: 'No orders in this range',
    emptyNote: 'Pick a different date range, or take an order to see it here.',
    voidedNote: 'This order was voided and was never paid for.',
  },

  dashboard: {
    title: 'Today',
    salesToday: "Today's sales",
    profitToday: "Today's profit",
    ordersToday: 'Orders today',
    openOrders: 'Open orders',
    bestSeller: 'Best seller today',
    busiestHour: 'Busiest hour',
    recent: 'Recent orders',
    newOrder: 'New order',
    noSalesTitle: 'No orders yet today',
    noSalesNote: 'Takings and profit will appear here as soon as the first order is settled.',
    profitLine: (sales: string, profit: string) => `You sold ${sales} and earned ${profit} profit.`,
  },

  order: {
    newOrder: 'New order',
    dineIn: 'Dine-in',
    takeaway: 'Takeaway',
    delivery: 'Delivery',
    chooseTable: 'Choose a table',
    customerName: 'Customer name',
    customerPhone: 'Phone',
    optional: 'optional',
    search: 'Search the menu',
    allItems: 'All',
    sendToKitchen: 'Send to kitchen',
    charge: 'Charge',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    serviceCharge: 'Service charge',
    emptyTitle: 'Nothing on this order yet',
    emptyNote: 'Tap an item on the left to add it.',
    soldOut: 'Sold out',
    fired: 'Sent',
    lineNote: 'Note for the kitchen',
    lineNotePlaceholder: 'e.g. less spicy, no onions',
    addToOrder: 'Add to order',
    void: 'Void',
    voidLine: 'Void this item',
    voidOrder: 'Void the whole order',
    voidReason: 'Why is this being voided?',
    voidReasonPlaceholder: 'e.g. customer changed their mind',
    managerPin: 'Manager PIN',
    paymentMethod: 'Payment',
    cash: 'Cash',
    card: 'Card',
    takePayment: 'Take payment',
    printBill: 'Print bill',
    reprint: 'Reprint bill',
    settled: 'Paid',
    noOpenOrders: 'No orders are open',
    startOrder: 'Start an order',
    resume: 'Resume',
    switchOrder: 'Switch order',
  },

  tables: {
    title: 'Tables',
    free: 'Free',
    occupied: 'Occupied',
    addTable: 'Add table',
    tableName: 'Table name',
    area: 'Area',
    seats: 'Seats',
    emptyTitle: 'No tables yet',
    emptyNote: 'Add your tables and the floor will show which are free at a glance.',
    disabledTitle: 'Tables are switched off',
    disabledNote: 'Turn dine-in tables on in Settings if this food point seats customers.',
  },

  menu: {
    title: 'Menu',
    addItem: 'Add item',
    addCategory: 'Add category',
    itemName: 'Item name',
    category: 'Category',
    price: 'Price',
    foodCost: 'Food cost',
    foodCostHint: 'Roughly what the ingredients cost. This is what profit is worked out from.',
    available: 'On the menu',
    soldOut: 'Sold out',
    modifierGroups: 'Options',
    emptyTitle: 'Your menu is empty',
    emptyNote: 'Add your first item and it will appear on the order screen straight away.',
    uncategorised: 'Uncategorised',
  },

  reports: {
    title: 'Reports',
    from: 'From',
    to: 'To',
    sales: 'Sales',
    profit: 'Profit',
    orders: 'Orders',
    byType: 'By order type',
    bestSellers: 'Best sellers',
    byHour: 'Sales by hour',
    voids: 'Voids',
    noneTitle: 'Nothing in this range',
    noneNote: 'Pick a different date range to see sales and profit.',
    reason: 'Reason',
  },

  settings: {
    title: 'Settings',
    business: 'Business',
    businessName: 'Business name',
    address: 'Address',
    phone: 'Phone',
    printing: 'Printing',
    customerPrinter: 'Customer bill printer',
    kitchenPrinter: 'Kitchen printer',
    kitchenPrinterHint: 'Leave blank to print kitchen tickets on the customer printer.',
    enableKitchenPrint: 'Print kitchen tickets',
    testPrint: 'Print a test',
    service: 'Charges',
    serviceCharge: 'Service charge %',
    currency: 'Currency symbol',
    dineIn: 'Dine-in',
    enableTables: 'This food point has tables',
    enableTablesHint: 'Turn this off for a pure takeaway counter — the Tables screen disappears.',
    security: 'Voids',
    managerPin: 'Manager PIN',
    managerPinHint: 'Ask for this PIN before voiding. Leave it blank to allow voids without one.',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    clearPin: 'Remove PIN',
    backup: 'Backup',
    backupNow: 'Back up now',
    restore: 'Restore from backup',
    lastBackup: 'Last backup',
    neverBackedUp: 'You have never backed up.',
    license: 'License',
    save: 'Save settings',
    saved: 'Settings saved.',
  },

  activation: {
    title: 'Activate Food Point',
    intro:
      'Send this Machine ID to the Code Hustlers office and they will send back a license key for this computer.',
    machineId: 'Machine ID',
    copy: 'Copy',
    copied: 'Copied',
    keyLabel: 'License key',
    keyPlaceholder: 'CH1...',
    activate: 'Activate',
    activating: 'Checking…',
    success: 'Activated. Opening the app…',
  },

  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    loading: 'Loading…',
    search: 'Search',
    none: '—',
    yes: 'Yes',
    no: 'No',
  },
};
